# Import necessary libraries
from pathlib import Path
from pptx import Presentation
from pptx.util import Pt
from typing import Dict, List

def build_presentation(slides: List[Dict], out_path: Path, title: str) -> Path:
    """ 
    Create a PowerPoint presentation from slides.
    @param slides (List[Dict]): Slides with 'title', 'bullets', 'notes'.
    @param out_path (Path): Destination .pptx file path.
    @param title (str): Overall presentation title for first slide.
    @return (Path): Path to the saved PowerPoint file. 
    """
    prs = Presentation()
    # Title slide
    title_slide_layout = prs.slide_layouts[0]
    slide_0 = prs.slides.add_slide(title_slide_layout)
    slide_0.shapes.title.text = title
    slide_0.placeholders[1].text = "Generated by DataOps + RAG"
    # Content slides
    content_layout = prs.slide_layouts[1]
    for s in slides:
        slide = prs.slides.add_slide(content_layout)
        slide.shapes.title.text = s["title"]
        tf = slide.placeholders[1].text_frame
        tf.clear()
        for b in s["bullets"]:
            p = tf.add_paragraph()
            p.text = b
            p.font.size = Pt(18)
        # Speaker notes
        notes_slide = slide.notes_slide
        notes_slide.notes_text_frame.clear()
        notes_slide.notes_text_frame.text = s["notes"]
    out_path.parent.mkdir(parents = True, exist_ok = True)
    prs.save(str(out_path))
    return out_path